config/routes.rb
LynxShare::Application.routes.draw do
  resources :users
  resources :links
  resources :tags
  resources :relationships

  post '/user_search' => 'users#search'
  post '/link_search' => 'links#search'
  post '/tag_search' => 'tags#search'
  delete "/signout" => "sessions#destroy"
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  root 'sessions#new'
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :user_links
  has_many :users, through: :user_links
  has_many :link_tags, dependent: :destroy
  has_many :tags, through: :link_tags
  validates :url, :presence => true
  validates :url, format: { with: /\A\S+\.\S+\Z/i }


  def create_tags(tags)
    tags.each do |tag|
      LinkTag.create(link: self, tag: Tag.find_or_create_by(name: tag))
    end
  end

end

app/models/link_tag.rb
class LinkTag < ActiveRecord::Base
  belongs_to :link
  belongs_to :tag
  validates :link_id,:tag_id, :presence => true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: :User, foreign_key: :follower_id
  belongs_to :followed_user, class_name: :User, foreign_key: :followed_user_id

  validates_uniqueness_of :follower_id, scope: :followed_user_id
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :link_tags
  has_many :links, through: :link_tags
  validates :name, :presence => true
  validates :name, length: { minimum: 2 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_links
  has_many :links, through: :user_links

  has_many :tags, through: :links

  has_many :follower_relationships, class_name: :Relationship, foreign_key: :followed_user_id
  has_many :followed_relationships, class_name: :Relationship, foreign_key: :follower_id
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followed_users, through: :followed_relationships, source: :followed_user

  validates :password, length: { minimum: 5 }
  validates :username, :presence => true
  validates :username, length: { minimum: 5 }

  has_secure_password

  def unfollowed_users(num_users = 10)
    followed_user_ids = self.followed_users.pluck(:id) << self.id
    User.where.not(id: followed_user_ids).take(num_users)
  end
end

app/models/user_link.rb
class UserLink < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  validates :user_id,:link_id, :presence => true
  # validates_uniqueness_of :link_id, :scope => :tag_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include LinksHelper

  def index
    @links = fetch_links(10,current_user.id)
    # binding.pry
  end

  def new
    @link = Link.new
  end

  def search
    link_array = fetch_links(10,current_user.id,params["currentString"])
    render(:partial => "link_container", :locals => {:links => link_array})
  end

  def create
    link = current_user.links.create(link_params)
    link.create_tags(format_tags(params[:tags]))
    redirect_to '/links'
  end

  def destroy
    Link.find(params[:id]).destroy
    redirect_to '/links'
  end
  private

  def link_params
      params.require(:link).permit(:url)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def index
    @users = current_user.followed_users
  end

  def create
    Relationship.create(followed_user_id: params[:relationship][:user_id], follower: current_user)
    redirect_to '/users'
  end

  def show

    @user = User.find(params[:id])
    @links = @user.links
  end

  def destroy
    Relationship.find(params[:id]).destroy
    redirect_to '/relationships'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
    @current_user= current_user
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to "/links"
    else
      # 'Invalid username/password combination'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
  # reset_session
      # flash[:success] = ["You have signed out successfully."]
      redirect_to root_url
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include TagsHelper
  def index
    @tags = fetch_tags(10,current_user.id)
    # @tags = current_user.tags
  end

  def show
    @tag = Tag.find(params[:id])
    @links = (current_user.links & @tag.links)
  end


  def search
    tag_array = fetch_tags(10,current_user.id,params["currentString"])
    render(:partial => "tag_container", :locals => {:tags => tag_array})
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  include UsersHelper

  def new
    @user = User.new
  end

  def index #show users that you are not following
    @user_array = current_user.unfollowed_users.uniq
    @relationship = Relationship.new
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    user_array = fetch_users(10,current_user.id,params["currentString"])
    @relationship = Relationship.new
    render(:partial => "user_container", :locals => {:users => user_array, :relationship => @relationship})
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome to the sample app!"
      redirect_to '/links'
    else
      render 'new', status: 422
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def add_hashtag(tag)
    "#" + tag
  end

  def fetch_links(capacity,user_id,str = "")
    loaded = false
    links = []
    while !loaded do
      current_user.links.each do |link|
        links.push(link) if link.url.include?(str)
        if links.size == capacity
          loaded = true
          break
        end
      end
      loaded = true
    end
    links.uniq
  end

  def pad(string)
    " " + string
  end

  def remove_hashtags(words)
    words.map!{ |word| word.gsub("#","") }
  end

  def format_tags(words_array)
    remove_hashtags(pad(words_array).scan(/[#\s](\S*)/).flatten)
  end

  def get_link_card(link)
    render :partial => "link", :locals => {:link => link}
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper # Currently overloading SessionsHelper, refactor into a concern
  def log_in(user)
    session[:user_id] = user.id
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end 
end

app/helpers/tags_helper.rb
module TagsHelper
  def fetch_tags(capacity,user_id,str = "")
    loaded = false
    tags = []
    while !loaded do
      current_user.tags.each do |tag|
        tags.push(tag) if tag.name.include?(str)
        if tags.size == capacity
          loaded = true
          break
        end
      end
      loaded = true
    end
    tags.uniq
 
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def fetch_users(capacity,user_id,str = "")
    loaded = false
    users = []
    while !loaded do
      current_user.unfollowed_users.each do |user|
        users.push(user) if user.username.include?(str) && user.id != user_id
        if users.size == capacity
          loaded = true
          break
        end
      end
      loaded = true
    end
    users.uniq
  end
end

app/views/layouts/_logout.html.erb
<% if @current_user %>
  <a href="/" class="item">
    <div class="side-item">
      <center>
        <i class="fa fa-sign-out"></i><%= link_to " Sign out", signout_path, method: :delete, class: "right-red" %>
      </center>
    </div>
  </a>
<% end %>

app/views/layouts/_welcome.html.erb
  <% if session[:user_id] != nil %>

    <div>
      <center>

    <p>Welcome <%= User.find(session[:user_id]).username.capitalize %></p>
      </center>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LynxShare</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=PT+Sans">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body style="background-color: #ECF0F1;">

<% if session[:user_id] != nil%>
<div class="ui red vertical demo thin sidebar menu active custom-bar">
<%= image_tag("lynx.png", class: "logo_image" )%>

  <%= render partial: "layouts/welcome" %>

  <a href="/links" class="item" style="color: #E74C3C">
    <div class="side-item">
      <center>
          <i class="fa fa-home fa-fw"></i>&nbsp; Home</a>
      </center>
    </div>
  </a>

  <a href="/relationships" class="item">
    <div class="side-item">
      <center>
          <i class="fa fa-globe"> Network</i>
      </center>
    </div>
  </a>

  <a href="/links/new" class="item" >
    <div class="side-item">
      <center>
          <i class="fa fa-plus"> Add Link</i>
      </center>
    </div>
  </a>

  <a href="/tags" class="item">
    <div class="side-item">
      <center>
          <i class="fa fa-slack"> Tags </i>
      </center>
  </div>

  <a href="/users" class="item">
    <div class="side-item">
      <center>
          <i class="fa fa-user"> People</i>
      </center>
  </div>
  </a>

  <%= render partial: "layouts/logout" %>

</div>

<% end %>

<%= yield %>

</body>
</html>

app/views/links/_link.html.erb
  <%= link_to link.url, link.url, class: "link" %> <br>
    <% link.tags.each do |tag| %>
      <%= link_to add_hashtag(tag.name), "/tags/#{tag.id}", class: "tag" %>
    <% end %>

app/views/links/_link_container.html.erb
<% links.each do |link| %>
<div class="card">
	<%#= form_for(link, method: :delete) do |f| %>
  <%= link_to image_tag("http://www.iconsdb.com/icons/download/red/x-mark-512.png", size: "10x10", align: "left"), link, method: :delete, data: {confirm: "Are you sure you'd like to delete this?"} %>
		<!-- <a href="javascript:{}" class="left vert-align" onclick="document.getElementById('edit_link_<%= link.id %>').submit()"><i class="fa fa-remove fa-fw"></i></a> -->
	<%# end %>
	<%= link_to link.url, link.url, class: "red link" %> <br>
  	<% link.tags.each do |tag| %>
  		<%= link_to add_hashtag(tag.name), "/tags/#{tag.id}", class: "tag" %>
  	<% end %>

</div>

<% end %>

app/views/links/_search.html.erb
<input data-search="linkSearchBar" placeholder="find links..." type="text" class="field-light">

app/views/links/index.html.erb
<div class="container-centered">
  <center>
    <h2>Links</h2>
    <%= render partial: "search" %>
    <div id ="linkzone">
      <%= render(:partial => "link_container", :locals => {:links => @links}) %>
    </div>
  </center>
</div>

app/views/links/new.html.erb
<!-- Form for creating a new link -->
<div class="container-centered">
  <center>
    <h2 class="right-red">Add A New Link</h2>
<%= form_for @link do |form| %>
	<%= form.text_field :url, :placeholder => "URL" %> <br>
	<input type="text" name="tags" placeholder="#tags"> <br>
	<%= form.submit(:class => 'button-blue-outline mb1') %>
<% end %>
</center>
</div>

app/views/relationships/_followers.html.erb
<div id="userzone">
  <% @users.uniq.each do |user| %>
  <div class="card" >

    <% @relationship = Relationship.find_by(follower_id: session[:user_id], followed_user: user) %>
    <%= link_to user.username, "relationships/#{user.id}", class: "red"%>
    <%= form_for(@relationship, method: :delete) do |f| %>
    <%= f.hidden_field :user_id, :value => user.id %>
    <%= f.submit "unfollow", :class => 'button-blue-outline mb1' %>
    <% end %>

  </div>
  <% end %>
</div>

app/views/relationships/index.html.erb
<div class="container-centered">
	<center>
		<h2>Check Out Your Network</h2>

		<%= render partial: "followers" %>

	</center>
</div>

app/views/relationships/show.html.erb
<div class="container-centered">
  <center>
<h2> <%= @user.username %> Links</h2>
<div id="linkzone">
<%= render(:partial => "links/link_container", :locals => {:links => @links}) %>
</div>
<center>
</div>

app/views/tags/_search.html.erb
<div>
  <input data-search="tagSearchBar" placeholder="find tags..." type="text" class="field-light">
</div>

app/views/tags/_tag_container.html.erb
<center><ul>
  <% tags.each do |tag| %>
  <div class="card">
    <li> <%= link_to add_hashtag(tag.name), tag_path(tag) %> </li>
  </div>
  <% end %>
</ul>
</center>

app/views/tags/index.html.erb
<div class="container-centered">
  <center>
    <h2> Tags</h2>
    <%= render partial: "search" %>
      <div id ="tagzone">
        <%= render(:partial => "tag_container", :locals => {:tags => @tags}) %>
      </div>
    </center>
  </div>

app/views/tags/show.html.erb
<div class="container-centered">
  <center>
    <div id="linkzone">
<h2> <%=add_hashtag(@tag.name)%> </h2>
<%= render(:partial => "/links/link_container", :locals => {:links => @links}) %>
  </div>
</center>
</div>

app/views/users/_search.html.erb
 <input data-search="userSearchBar" placeholder="find users..."  type="text" class="field-light">

app/views/users/_user_container.html.erb
  <div id="userzone">
  <% users.each do |user| %>
    <div class="card">
    <p class="red"> <%= user.username%> </p>
    <%= form_for(relationship) do |f| %>
      <%= f.hidden_field :user_id, :value => user.id %>
      <%= f.submit "follow", :class => 'button-blue-outline mb1' %>
      </div>
    <% end %>
  <% end %>
  </div>

app/views/users/index.html.erb
<div class="container-centered">
  <center>
    <h2> Discover Users</h2>
    <%= render partial: "search" %>
    <div id ="userzone">
      <%= render(:partial => "user_container", :locals => {:users => @user_array, :relationship => @relationship}) %>
    </div>
  </center>
</div>

app/views/users/new.html.erb
<div class="container-centered">
<center>

<h1>Register</h1>
	<%= form_for(@user) do |form|%>
		<%= form.label :username %>
		<%= form.text_field :username %> <br>

		<%= form.label :password %>
		<%= form.password_field :password %>  <br>

		<%= form.label :confirm_password %>
		<%= form.password_field :password_confirmation %> <br>

		<%= form.submit "Create Account" %>
	<% end %>
</center>
</div>